# Generated by Django 3.1.7 on 2021-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210603_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='trendingnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.CharField(max_length=10)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='media')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
